#!/usr/bin/env python3
"""Generate STL for ClawPilot display enclosure.

Coordinate system (origin = bottom-left-back corner):
  X: left → right  (width)
  Y: bottom → top  (height)
  Z: back → front  (depth)
"""
import struct
import math


def normalize(v):
    l = math.sqrt(sum(x * x for x in v))
    return tuple(x / l for x in v) if l > 1e-10 else (0.0, 0.0, 1.0)


def face_normal(tri):
    ax, ay, az = tri[1][0]-tri[0][0], tri[1][1]-tri[0][1], tri[1][2]-tri[0][2]
    bx, by, bz = tri[2][0]-tri[0][0], tri[2][1]-tri[0][1], tri[2][2]-tri[0][2]
    return normalize((ay*bz - az*by, az*bx - ax*bz, ax*by - ay*bx))


def write_stl(tris, path):
    with open(path, 'wb') as f:
        header = b'ClawPilot Display Enclosure - generated by generate_enclosure.py'
        f.write(header[:80].ljust(80, b'\x00'))
        f.write(struct.pack('<I', len(tris)))
        for tri in tris:
            n = face_normal(tri)
            f.write(struct.pack('<3f', *n))
            for v in tri:
                f.write(struct.pack('<3f', *v))
            f.write(b'\x00\x00')
    print(f"Wrote {len(tris)} triangles → {path}")


def quad(p1, p2, p3, p4):
    """Split a CCW quad into 2 triangles (outward normal faces viewer)."""
    return [(p1, p2, p3), (p1, p3, p4)]


# ─── Dimensions (mm) ────────────────────────────────────────────────────────
W  = 89.3   # total outer width  (85.3 display + 2 mm bezel × 2 sides)
H  = 55.5   # total outer height
D  = 46.0   # total outer depth
t  = 2.0    # wall / bezel thickness

dW = 85.3          # display opening width
dH = H - 2 * t     # display opening height = 51.5 mm

# Display opening corners (on the front outer face, z = D)
dx0, dx1 = t, t + dW          # 2.0, 87.3
dy0, dy1 = t, t + dH          # 2.0, 53.5

# Recess: display sits at z = D - t (flush with back of front wall)
rz = D - t   # z = 44.0

tris = []

# ─── OUTER SURFACES ──────────────────────────────────────────────────────────

# Bottom outer  (facing −Y)
tris += quad((0,0,0), (0,0,D), (W,0,D), (W,0,0))

# Top outer  (facing +Y)
tris += quad((0,H,0), (W,H,0), (W,H,D), (0,H,D))

# Left outer  (facing −X)
tris += quad((0,0,0), (0,H,0), (0,H,D), (0,0,D))

# Right outer  (facing +X)
tris += quad((W,0,0), (W,0,D), (W,H,D), (W,H,0))

# ─── FRONT FACE OUTER (z = D, facing +Z) ─────────────────────────────────
# Four strips forming the bezel frame around the display opening

# Bottom strip  y: 0 → dy0
tris += quad((0,0,D),   (W,0,D),   (W,dy0,D), (0,dy0,D))
# Top strip     y: dy1 → H
tris += quad((0,dy1,D), (W,dy1,D), (W,H,D),   (0,H,D))
# Left strip    x: 0 → dx0,  y: dy0 → dy1
tris += quad((0,dy0,D), (dx0,dy0,D), (dx0,dy1,D), (0,dy1,D))
# Right strip   x: dx1 → W,  y: dy0 → dy1
tris += quad((dx1,dy0,D), (W,dy0,D), (W,dy1,D), (dx1,dy1,D))

# ─── FRONT FACE INNER (z = rz, facing −Z) ───────────────────────────────
# Same frame but winding reversed so normal points inward (−Z)

# Bottom strip
tris += quad((0,0,rz),   (0,dy0,rz), (W,dy0,rz), (W,0,rz))
# Top strip
tris += quad((0,dy1,rz), (0,H,rz),   (W,H,rz),   (W,dy1,rz))
# Left strip
tris += quad((0,dy0,rz), (0,dy1,rz), (dx0,dy1,rz), (dx0,dy0,rz))
# Right strip
tris += quad((dx1,dy0,rz), (dx1,dy1,rz), (W,dy1,rz), (W,dy0,rz))

# ─── DISPLAY RECESS INNER EDGES (the 4 walls of the 2 mm deep recess) ────
# These are the faces you see at the edge of the display cutout, depth = t

# Bottom recess edge (facing −Y into recess)
tris += quad((dx0,dy0,rz), (dx1,dy0,rz), (dx1,dy0,D), (dx0,dy0,D))

# Top recess edge (facing +Y into recess)
tris += quad((dx0,dy1,D), (dx1,dy1,D), (dx1,dy1,rz), (dx0,dy1,rz))

# Left recess edge (facing −X into recess)
tris += quad((dx0,dy0,D), (dx0,dy1,D), (dx0,dy1,rz), (dx0,dy0,rz))

# Right recess edge (facing +X into recess)
tris += quad((dx1,dy0,rz), (dx1,dy1,rz), (dx1,dy1,D), (dx1,dy0,D))

# ─── INNER WALL SURFACES (facing into the box cavity) ────────────────────
# Left inner  (x = t, facing +X)  full height, z: 0 → rz
tris += quad((t,0,rz), (t,H,rz), (t,H,0), (t,0,0))

# Right inner (x = W-t, facing −X)  full height, z: 0 → rz
tris += quad((W-t,0,0), (W-t,H,0), (W-t,H,rz), (W-t,0,rz))

# Top inner (y = H-t, facing −Y)  x: t → W-t,  z: 0 → rz
tris += quad((t,H-t,0), (t,H-t,rz), (W-t,H-t,rz), (W-t,H-t,0))

# Bottom inner (y = t, facing +Y)  x: t → W-t,  z: 0 → rz
tris += quad((t,t,rz), (t,t,0), (W-t,t,0), (W-t,t,rz))

# ─── BACK EDGE RIMS (at z = 0, close each wall cross-section) ────────────
# These faces cap the wall "tubes" at the back so the shell is watertight.
# Leaving the back open = no back panel, but the wall cross-sections are capped.

# Bottom wall back rim (y: 0 → t, x: 0 → W)
tris += quad((0,0,0), (W,0,0), (W,t,0), (0,t,0))

# Top wall back rim (y: H-t → H, x: 0 → W)
tris += quad((0,H-t,0), (W,H-t,0), (W,H,0), (0,H,0))

# Left wall back rim (x: 0 → t, y: 0 → H)
tris += quad((0,0,0), (0,H,0), (t,H,0), (t,0,0))

# Right wall back rim (x: W-t → W, y: 0 → H)
tris += quad((W-t,0,0), (W-t,H,0), (W,H,0), (W,0,0))

# ─── Write ────────────────────────────────────────────────────────────────
write_stl(tris, 'enclosure.stl')

print()
print("Enclosure dimensions:")
print(f"  Outer:          {W:.1f} × {H:.1f} × {D:.1f} mm  (W × H × D)")
print(f"  Wall thickness: {t:.1f} mm")
print(f"  Display opening:{dW:.1f} × {dH:.1f} mm")
print(f"  Display recess: {t:.1f} mm deep")
print("  Back: open")
